from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^accounts/profile/$', 'readmore.main.views.profile_self', name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', 'readmore.main.views.article_overview', name='article_overview'),
    url(r'^profile/(?P<user_id>\w+)$', 'readmore.main.views.profile', name='profile'),
    url(r'^about/', 'readmore.main.views.about', name='about'),
    url(r'^add_to_history/$', 'readmore.main.views.history', name='history'),
    url(r'^api/stats/total/views/?$',
        'readmore.main.views.api_get_total_views',
        name='api_get_total_views'),
    url(r'^api/stats/total/covers/?$',
        'readmore.main.views.api_get_total_covers',
        name='api_get_total_covers'),
    url(r'^api/stats/total/ratings/like/?$',
        'readmore.main.views.api_get_total_like_ratings',
        name='api_get_total_like_ratings'),
    url(r'^api/stats/total/ratings/difficulty/?$',
        'readmore.main.views.api_get_total_difficulty_ratings',
        name='api_get_total_difficulty_ratings'),
    url(r'^api/list/events/last/?$',
        'readmore.main.views.api_get_last_events',
        name='api_get_last_events'),
    url(r'^api/list/users/active/?$',
        'readmore.main.views.api_get_most_active_users',
        name='api_get_most_active_users'),
    url(r'^api/list/articles/hardest/?$',
        'readmore.main.views.api_get_hardest_articles',
        name='api_get_hardest_articles'),
)
